# Generated by Django 3.0.6 on 2020-05-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='comleted',
            new_name='completed',
        ),
    ]
